INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('01' ,	'Alava'                     );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('02' ,	'Albacete'                  );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('03' ,	'Alicante'                  );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('04' ,	'Almeria'                   );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('05' ,	'Avila'                     );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('06' ,	'Badajoz'                   );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('07' ,	'Islas Baleares'            );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('08' ,	'Barcelona'                 );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('09' ,	'Burgos'                    );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('10' ,	'Caceres'                   );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('11' ,	'Cadiz'                     );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('12' ,	'Castellon'                 );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('13' ,	'Ciudad Real'               );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('14' ,	'Cordoba'                   );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('15' ,	'Coruña'                    );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('16' ,	'Cuenca'                    );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('17' ,	'Girona'                    );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('18' ,	'Granada'                   );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('19' ,	'Guadalajara'               );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('20' ,	'Guipuzcoa'                 );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('21' ,	'Huelva'                    );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('22' ,	'Huesca'                    );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('23' ,	'Jaen'                      );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('24' ,	'León'                      );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('25' ,	'Lleida'                    );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('26' ,	'La Rioja'                  );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('27' ,	'Lugo'                      );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('28' ,	'Madrid'                    );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('29' ,	'Málaga'                    );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('30' ,	'Murcia'                    );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('31' ,	'Navarra'                   );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('32' ,	'Ourense'                   );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('33' ,	'Asturias'                  );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('34' ,	'Palencia'                  );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('35' ,	'Las Palmas de Gran Canaria');
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('36' ,	'Pontevedra'                );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('37' ,	'Salamanca'                 );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('38' ,	'Santa Cruz de Tenerife'    );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('39' ,	'Cantabria'                 );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('40' ,	'Segovia'                   );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('41' ,	'Sevilla'                   );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('42' ,	'Soria'                     );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('43' ,	'Tarragona'                 );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('44' ,	'Teruel'                    );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('45' ,	'Toledo'                    );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('46' ,	'Valencia'                  );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('47' ,	'Valladolid'                );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('48' ,	'Vizcaya'                   );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('49' ,	'Zamora'                    );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('50' ,	'Zaragoza'                  );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('51' ,	'Ceuta'                     );
INSERT INTO centrosacad.tbcpo (NCodigo, Ciudad) values ('52' ,	'Melilla'                   );