-- MySQL Script generated by MySQL Workbench
-- Fri Dec  8 22:56:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema centrosacad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema centrosacad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `centrosacad` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `centrosacad` ;

-- -----------------------------------------------------
-- Table `centrosacad`.`tbtipdoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centrosacad`.`tbtipdoc` (
  `Id` INT NOT NULL,
  `NomTDo` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centrosacad`.`tbcpo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centrosacad`.`tbcpo` (
  `NCodigo` VARCHAR(2) NOT NULL,
  `Ciudad` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`NCodigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centrosacad`.`tbProf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centrosacad`.`tbProf` (
  `IdProf` VARCHAR(6) NOT NULL,
  `Nombre` VARCHAR(15) NOT NULL,
  `Apellidos` VARCHAR(31) NOT NULL,
  `Id` INT NOT NULL COMMENT 'Tipo de documento',
  `numDoc` VARCHAR(50) NOT NULL,
  `FecNac` DATETIME NOT NULL,
  `FecAlt` DATETIME NOT NULL,
  `Direccion` VARCHAR(255) NOT NULL,
  `Localidad` VARCHAR(255) NOT NULL,
  `nCodigo` VARCHAR(2) NOT NULL COMMENT 'Código de provincia',
  `codPos` VARCHAR(5) NOT NULL,
  `Observ` VARCHAR(255) NULL,
  `Tel` VARCHAR(9) NULL,
  `Mov` VARCHAR(9) NULL,
  `email` VARCHAR(100) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdProf`, `Id`, `nCodigo`),
  INDEX `fk_tbtipdoc_idx` (`Id` ASC) VISIBLE,
  INDEX `fk_tbProvincias_idx` (`nCodigo` ASC) VISIBLE,
  CONSTRAINT `fk_tbtipdoc2`
    FOREIGN KEY (`Id`)
    REFERENCES `centrosacad`.`tbtipdoc` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProvincias2`
    FOREIGN KEY (`nCodigo`)
    REFERENCES `centrosacad`.`tbcpo` (`NCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centrosacad`.`tbUsuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centrosacad`.`tbUsuarios` (
  `nombreUsuario` VARCHAR(8) NOT NULL COMMENT 'Nombre de usuario con el que acceder a la aplicación',
  `password` VARCHAR(100) NOT NULL,
  `nivelAcceso` INT NOT NULL,
  `nombreCompleto` VARCHAR(50) NOT NULL,
  `codCentro` INT NOT NULL,
  `activo` TINYINT(1) NULL,
  `idProfesor` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`nombreUsuario`, `idProfesor`),
  INDEX `fk_tbProf_idx_idx` (`idProfesor` ASC) VISIBLE,
  CONSTRAINT `fk_tbProf_idx`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `centrosacad`.`tbProf` (`IdProf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci
COMMENT = 'Tabla que almacena los datos de acceso de los usuarios';


-- -----------------------------------------------------
-- Table `centrosacad`.`tbRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centrosacad`.`tbRoles` (
  `idRole` VARCHAR(8) NOT NULL,
  `roleName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centrosacad`.`tbUsuariosRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centrosacad`.`tbUsuariosRoles` (
  `nombreUsuario` VARCHAR(8) NOT NULL,
  `idRole` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`nombreUsuario`, `idRole`),
  INDEX `fk_tbUsuarios_has_tbRoles_tbRoles1_idx` (`idRole` ASC) VISIBLE,
  INDEX `fk_tbUsuarios_has_tbRoles_tbUsuarios_idx` (`nombreUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_tbUsuarios_has_tbRoles_tbUsuarios`
    FOREIGN KEY (`nombreUsuario`)
    REFERENCES `centrosacad`.`tbUsuarios` (`nombreUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tbUsuarios_has_tbRoles_tbRoles1`
    FOREIGN KEY (`idRole`)
    REFERENCES `centrosacad`.`tbRoles` (`idRole`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `centrosacad`.`tbNivFor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centrosacad`.`tbNivFor` (
  `idNivel` INT NOT NULL,
  `NomNivel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idNivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centrosacad`.`tbAlu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centrosacad`.`tbAlu` (
  `idAlu` VARCHAR(8) NOT NULL COMMENT 'Código de alumno',
  `TDoAlu` INT NOT NULL COMMENT 'Tippo de documento de identificación del alumno',
  `NDoAlu` VARCHAR(20) NOT NULL COMMENT 'Número de documento identificativo',
  `NomAlu` VARCHAR(50) NOT NULL COMMENT 'Nomnbre del alumno',
  `Ap1Alu` VARCHAR(50) NOT NULL COMMENT 'Primer apellido',
  `Ap2Alu` VARCHAR(45) NULL COMMENT 'Segundo apellido',
  `MovAlu` VARCHAR(9) NULL COMMENT 'Número de teléfono movil del alumno',
  `FijAlu` INT NULL COMMENT 'Némero de teléfono fijo del alumno',
  `DirAlu` VARCHAR(150) NOT NULL COMMENT 'Dirección del alumno',
  `CpoAlu` VARCHAR(5) NOT NULL COMMENT 'Código postal',
  `LocAlu` VARCHAR(45) NOT NULL COMMENT 'Localidad ',
  `NFoAlu` INT NOT NULL COMMENT 'Nivel formativo del alumno',
  `EmaAlu` VARCHAR(150) NULL COMMENT 'Email del alumno',
  `DesAlu` TINYINT(1) NOT NULL COMMENT 'Indica si el alumno está desempleado',
  `EmpAlu` VARCHAR(8) NULL COMMENT 'Código de la empresa a la que pertenece el alumno',
  `IntAlu` LONGTEXT NULL,
  `codProAlu` VARCHAR(2) NOT NULL COMMENT 'Código de provincia',
  `IdCen` INT NOT NULL,
  `FecNac` DATETIME NULL,
  `alND` TINYINT(1) NOT NULL COMMENT 'Indica si el alumno ha causado algún problema en cursos anteriores',
  `autCesDat` TINYINT(1) NULL COMMENT 'Indica si autoriza la cesión de datos',
  `autComCom` TINYINT(1) NOT NULL COMMENT 'Indica si el alumno autoriza las comunicaciones comerciales',
  `responsable` VARCHAR(50) NULL COMMENT 'Responsable legal del alumno si es menor de edad. Fuera de uso',
  `colegio` VARCHAR(100) NULL COMMENT 'Colegio del alumno si está en edad escolar. Fuera de uso',
  `curso` VARCHAR(25) NULL COMMENT 'Curso del alumno si está en edad escolar. Fuera de uso',
  PRIMARY KEY (`idAlu`, `NFoAlu`, `codProAlu`, `TDoAlu`),
  INDEX `fk_tbNiveles_idx` (`NFoAlu` ASC) VISIBLE,
  INDEX `fk_tbProvincias_idx` (`codProAlu` ASC) VISIBLE,
  INDEX `fk_tbTipDoc_idx` (`TDoAlu` ASC) VISIBLE,
  CONSTRAINT `fk_tbNiveles1`
    FOREIGN KEY (`NFoAlu`)
    REFERENCES `centrosacad`.`tbNivFor` (`idNivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProvincias1`
    FOREIGN KEY (`codProAlu`)
    REFERENCES `centrosacad`.`tbcpo` (`NCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbTipDoc1`
    FOREIGN KEY (`TDoAlu`)
    REFERENCES `centrosacad`.`tbtipdoc` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centrosacad`.`tbprofarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centrosacad`.`tbprofarea` (
  `IdProf` VARCHAR(6) NOT NULL,
  `IdArea` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdArea`, `IdProf`),
  CONSTRAINT `fk_prof_has_area`
    FOREIGN KEY (`IdProf`)
    REFERENCES `centrosacad`.`tbProf` (`IdProf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
